Repository Curiosity-org/Gipsy, pull requests merged in 2023-03, with the labels that each got.

#187 🧾 Remove dev announcement in stable branches
  docs/conf.py
Labels: documentation

#178 :construction_worker: ci: add dependabot config
  .github/dependabot.yml
Labels: workflow

#116 ✅ Fix style issues
  .pylintrc
  bot/args.py
  bot/checks.py
  bot/utils/configManager.py
  bot/utils/errors.py
  bot/utils/gunivers.py
  bot/utils/languages.py
  bot/utils/sconfig.py
  bot/utils/timeclass.py
  core/config.py
  docs/conf.py
  plugins/__template__/__template__.py
  plugins/admin/admin.py
  plugins/admin/credits.md
  plugins/antikikoo/antikikoo.py
  plugins/ban/ban.py
  plugins/ban/events/autoban.py
  plugins/ban/events/baldban.py
  plugins/ban/events/bothban.py
  plugins/ban/events/just_a_message.py
  plugins/ban/events/reverse.py
  plugins/ban/events/rickroll.py
  plugins/channelArchive/channelArchive.py
  plugins/contact/contact.py
  plugins/contact/credits.md
  plugins/contact/test.py
  plugins/general/credits.md
  plugins/general/general.py
  plugins/giveaways/credits.md
  plugins/giveaways/giveaways.py
  plugins/groups/credits.md
  plugins/groups/groups.py
  plugins/help/help.py
  plugins/hypesquad/credits.md
  plugins/hypesquad/hypesquad.py
  plugins/inviteTracker/inviteTracker.py
  plugins/logs/logs.py
  plugins/messageManager/messageManager.py
  plugins/misc/credits.md
  plugins/misc/misc.py
  plugins/permissions/permissions.py
  plugins/quizz/QuiPyQuizz.py
  plugins/quizz/credits.md
  plugins/quizz/quipyquizz.py
  plugins/quizz/quizz.py
  plugins/roleLink/roleLink.py
  plugins/rss/rss.py
  plugins/rss/setup.py
  plugins/thanks/credits.md
  plugins/thanks/thanks.py
  plugins/voice/credits.md
  plugins/voice/voice.py
  plugins/welcome/credits.md
  plugins/welcome/welcome.py
  plugins/wormhole/wormhole.py
  plugins/xp/xp.py
  setup.py
  start.py
  utils.py
Labels: style
